### ISSUE TITLE
Validator incorrectly thinks VALARM can be before eventprops

### ISSUE THREAD

**Issue by swhiteman** [CorrectICS/correctics-feedback#1]
### What happened?

The validator passes this file without warnings/notices/errors:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Microsoft Corporation//Outlook 11.0 MIMEDIR//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20251016T041331Z
UID:20251016T041331Z-1266201208@ics.agical.io
DTSTART:20251112T190000Z
DTEND:20251112T230000Z
SUMMARY:Logi Work Montréal
DESCRIPTION:Logi Work Montréal
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT1M
DESCRIPTION:Alarm: Logi Work Montréal
ACTION:DISPLAY
END:VALARM
LOCATION:Maison Alcan\, 2100 Stanley Street
END:VEVENT
END:VCALENDAR
```

However, it’s actually broken per RFC 5545. The ABNF specifies eventprops must come *before* VALARM(s):

https://www.rfc-editor.org/rfc/rfc5545.html#:~:text=eventprop%20*alarmc

Note this matters a lot in the real world. New Outlook will not display the Location when it appears after VALARM.

### Steps to reproduce

Go to validator, paste above ICS file.

### Expected behavior

Fatal error.

### Environment

Chrome Windows latest

### Severity

None

**Comment by f1yankees** [comment]
Thanks for the clear report. You’re right. Per RFC 5545, all VEVENT properties must appear before any VALARM components, so having LOCATION after a VALARM shouldn't work and can break clients.

We’ve added a new rule to flag this as a fatal validation error and we also implemented an autofix.

If you’re able, could you please re-test with the updated validator (or run API with autofix=1) and confirm Outlook shows the Location as expected? If so, we’ll close this out.

**Comment by swhiteman** [comment]
Thanks for checking this out. I confirm the validator catches it. The “Create Key" button doesn’t appear to be working for my new Free account, though, so I can’t check the autofix.

**Comment by f1yankees** [comment]
Thanks, I found a Turnstile issue and corrected it. key generation should be good now.

**Comment by swhiteman** [comment]
Got the key but `autofix=1` doesn’t seem to fully work, I still get

```json
  "repair": {
    "applied": true,
    "partial": true,
    "included": false,
    "count": 2,
    "message": "Partial fixes applied — errors remain that require manual changes."
  },
```

**Comment by f1yankees** [comment]
Hi there, that response looks generally right if you are on a free plan where autofix=1 will return a summary but not give you the fixed file. Not all errors can be autofixed, so the partial fix indicates certain errors are not deterministic and require the user to manually make an edit (e.g. time zone is missing - but which one did you want?).

I appreciate the feedback though, if you want to try it out I can give you a free upgrade to Pro for a bit on any of our utility apps and you can experiment (CorrectICS, CorrectVCF, CorrectFeed).
